#!/bin/bash

echo "=== Тесты VPS / Remnano Node ==="

while true; do
    echo ""
    echo "Выберите тест для запуска (введите номер) или Exit для выхода:"
    PS3="Введите номер опции: "
    options=(
        "Тест на локацию"
        "Проверка IP на блокировки CheckPlace"
        "Проверка IP на блокировки Multination"
        "Модифицированный iperf3 (bench.tlab.pw)"
        "iperf3 по DigneZzZ (bench.gig.ovh)"
        "Проверка скорости к зарубежным провайдерам (bench.sh)"
        "Проверка блокировки аудио в Instagram"
        "Yabs тест на производительность"
        "Проверка скорости к российским провайдерам incdev / artydev"
        "Exit"
    )

    select opt in "${options[@]}"; do
        case $REPLY in
            1) bash <(wget -qO- https://ipregion.vrnt.xyz); break ;;
            2) bash <(curl -Ls IP.Check.Place) -l en; break ;;
            3) bash <(curl -L -s check.unlock.media) -E en -R 0; break ;;
            4) wget -qO- bench.tlab.pw | bash; break ;;
            5) wget -qO- bench.gig.ovh | bash; break ;;
            6) wget -qO- bench.sh | bash; break ;;
            7) bash <(curl -L -s https://bench.openode.xyz/checker_inst.sh); break ;;
            8) curl -sL yabs.sh | bash -s -- -4; break ;;
            9) wget -qO- speedtest.incdev.net | bash; wget -qO- speedtest.artydev.ru | bash; break ;;
            10) echo "Выход из тестов."; exit 0 ;;
            *) echo "Неверный выбор. Введите номер от 1 до ${#options[@]}."; break ;;
        esac
    done
done
