#!/bin/bash

while true; do
  clear
  echo "🦊 Шпаргалка для теста VPS"
  echo "Выберите тест:"
  echo "1) Тест на локацию"
  echo "2) Проверка IP (CheckPlace)"
  echo "3) Проверка IP (Multination)"
  echo "4) Модифицированный iperf3 (n_teslatel)"
  echo "5) iperf3 тест (DigneZzZ)"
  echo "6) iperf3 тест (bench.sh, зарубежные)"
  echo "7) Проверка блокировки аудио Instagram"
  echo "8) YABS тест на производительность"
  echo "9) Speedtest incdev (Россия)"
  echo "10) Speedtest artydev (Россия)"
  echo "0) Выйти"
  echo
  read -p "Введите номер теста: " choice

  case $choice in
    1) bash <(wget -qO- https://ipregion.vrnt.xyz) ;;
    2) bash <(curl -Ls IP.Check.Place) -l en ;;
    3) bash <(curl -L -s check.unlock.media) -E en -R 0 ;;
    4) wget -qO- bench.tlab.pw | bash ;;
    5) wget -qO- bench.gig.ovh | bash ;;
    6) wget -qO- bench.sh | bash ;;
    7) bash <(curl -L -s https://bench.openode.xyz/checker_inst.sh) ;;
    8) curl -sL yabs.sh | bash -s -- -4 ;;
    9) wget -qO- speedtest.incdev.net | bash ;;
    10) wget -qO- speedtest.artydev.ru | bash ;;
    0) echo "Выход..."; exit 0 ;;
    *) echo "Неверный выбор, попробуйте снова"; sleep 2 ;;
  esac

  echo
  read -p "Нажмите Enter для возврата в меню..."
done
